version: '2.1'

services:
  web:
    extends:
      file: common.yml
      service: web
    environment:
      - NODE_ENV=development
    expose:
      - "80"
      - "56745"
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "56745:56745"
